### ISSUE TITLE
Both Material and Bootstrap paginators don't work with new version of NGrid

### ISSUE THREAD

**Issue by tamtakoe** [shlomiassaf/ngrid#157]
#### What is the current behavior?
Nothing

#### What are the steps to reproduce?
https://codesandbox.io/s/paginator-bug-jvsxn

**Comment by shlomiassaf** [comment]
@tamtakoe You forgot to add the `usePagination` attribute, which is actually a plugin.

Without it, the whole pagination code is "tree shaked" because it's not being used and this is why plugin via directives was chosen for pagination and other ngrid fetures.

I've also added the UX presentation of the pagination which can also be set from the outside in a global registry component.

Here is the working version: https://codesandbox.io/s/paginator-bug-forked-3f1d2?file=/src/app/app.component.html:333-346
