### ISSUE TITLE
columns shift in specific width configuration and virtual scroll 

### ISSUE THREAD

**Issue by shlomiassaf** [shlomiassaf/ngrid#57]
#### What is the expected behavior?

Columns should not shift when scrolling

#### What is the current behavior?

When column widths are defined in a way that one column has no width defined, and only minWidth set, when scrolling a longer lists columns get shifted.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: [stackblitz.com/edit/pebula-ngrid-starter](https://stackblitz.com/edit/pebula-ngrid-starter?file=app%2Fapp.component.ts)<br/>

![image](https://user-images.githubusercontent.com/1933165/68948185-38182880-07af-11ea-9842-51c3847445b3.png)
![image](https://user-images.githubusercontent.com/1933165/68948203-42d2bd80-07af-11ea-8a3d-ef3b6bd25b84.png)

cc @t00

**Comment by shlomiassaf** [comment]
@t00 I tried reproducing this, but no luck, can you help?

https://stackblitz.com/edit/pebula-ngrid-starter-lkwpvc?file=app/app.component.ts

**Comment by t00** [comment]
I was able to reproduce the problem after making some changes: https://stackblitz.com/edit/pebula-ngrid-starter-1zlhez
I cut down the number of directives to make it simplet and changed the row height to 30px by:

1. adding a style
```
.pbl-ngrid-row {
  min-height: 30px !important;
}
```

2. Setting the vScrollFixed attribute with a value of 30:

`vScrollFixed="30"`

Looks like changing the row height causes the issue but not immediately.

Steps to reproduce:

1. Open the grid in a maximized browser window
2. Scroll down a little and back to top
3. Make window not maximized
4. Scroll down a little and back to top
5. Make window maximized
6. Scroll down - you will see the coming from the bottom with incorrect sizes

Surely grid after minimizing/maximizing loses the information about virtual row height somehow and for some reason this is happening without window maximizing in the app I am working on, possibly due to the parent component being tam-splitter container changing the size dynamically doing initialization.

**Comment by t00** [comment]
I noticed that for the incorrectly sized row, width and max-width are changed to pixels while correctly sized rows have percentage as specified in column definitions.

**Comment by t00** [comment]
An update - after removing vScrollFixed="30" (defaults to vScrollAuto) and the custom row height (defaults to 48px) the problem is still reproducible. Only maximizing and restoring window twice is needed to trigger the problem - that should narrow down the problem as more generic.

**Comment by shlomiassaf** [comment]
I was able to reproduce it...

For some reason, resize events are not fired or fired but does not result in updates to the cells.

I'll check

**Comment by t00** [comment]
Many thanks, much appreciated!

**Comment by shlomiassaf** [comment]
@t00 Note that the latest release (1.0.0-rc.10) does not fix this yet, it includes the other things you pushed.

**Comment by t00** [comment]
@shlomiassaf sure, no worries - thank you for including these.

Also when experimenting I found much easier way to reproduce the issue above - just open https://pebula-ngrid-starter-1zlhez.stackblitz.io/ in a smaller window and once it loads, resize window.

**Comment by shlomiassaf** [comment]
Lol, was just about to write you about this way to reproduce it...

Anyways, what happens is that when you load the grid on a small viewport the cells update accordingly but when you maximize, resize events kicks in to update, however the raw cells are never actually updated...

This does not occur when resizing through API or mouse drag because that operation will trigger a direct update to the widths...

It does happen in this case because the resize events are indirect and the handlers for those does not properly trigger updates to the cell

**Comment by t00** [comment]
What is interesting is why when scrolling down (without resizing), bottom rows have their widths not updated.

**Comment by shlomiassaf** [comment]
It's virtual scroll so there are no "bottom" rows....

All row elements (and their child cell elements) are not removed, their data is just replaced when you scroll, based on the scroll offset.

Virtual scrolling will render row elements that will fit the viewport of the grid but it also require some buffer to perform well so top and bottom ends get some more rows that are not visible...
 
The buffer length might change so sometimes rows are added/removed from the buffer but i've checked and they get the same width's.

**Comment by shlomiassaf** [comment]
Ok, this was a big change, let's hope it doesn't have regressions :(
