### ISSUE TITLE
wrong dynamic width calculation 

### ISSUE THREAD

**Issue by shlomiassaf** [shlomiassaf/ngrid#58]
#### What is the expected behavior?

Total width of all column should reflect the total width of the grid or the total width of the **minWidth** definitions

#### What is the current behavior?

When **minWidth** is not set the total width of all column exceeds the actual total width by 15 pixels, probably due to some logic being skipped when no minWidth's are set.

#### What are the steps to reproduce?

I'm unable to reproduce this on [StackBlitz](https://stackblitz.com/edit/pebula-ngrid-starter-gplr8r?file=app%2Fapp.component.ts) however, I'm able to reproduce it in the demo application.

This seems like a CSS style override issue or something that happens due to a plugin that runs within the context of the demo app but not in the stackblitz demo.

#### Is there anything else we should know?

This might also happen when **minWidth** is set once, but not in every instance...

I can also happen on some other very specific width definitions which usually ignore setting width or minWidth...

**Comment by shlomiassaf** [comment]
@t00 I would appreciate if you give the stackblitz demo a try, and attempt to reproduce it there, I couldn't...

**Comment by shlomiassaf** [comment]
@t00  can you check if rc11 solved this? I think it might.
Thanks

**Comment by t00** [comment]
Looks like it is behaving perfectly now, i will be back on Friday to double check it. Many thanks!

**Comment by t00** [comment]
After more testing, I could not find any issues in rc11 related to column shifting. I could find however a problem if only a single column, without percentage was added to a grid which caused Firefox (only) to render this column with a calculated width of 0px making cell contents invisible (row frame/bg was there). Adding width='100%' for the column helped.

Since I have noticed rc12 build, I would need to re-test this scenario but consider above as a corner case, maybe you will have an idea what could have gone wrong.

All in all this bug is solved as far as I can see.
