### ISSUE TITLE
Column widths in the header are not in line with rows on Firefox (1.0.0-rc.12)

### ISSUE THREAD

**Issue by t00** [shlomiassaf/ngrid#69]
Recent refactoring (changing table to grid) introduced an issue with Firefox when resizing of ngrid (i.e. by resizing window) is not applied to the header correctly.

The cause is probably that pbl-ngrid-row-visually-hidden style on Firefox must be optimized as not visible causing it's dimensions to be not changed when resizing.

Chrome is rendering columns just fine, total width is correctly updated.

Simply changing visibility to hidden !important instead of collapsed !important seems to help but probably needs further investigation.

Hope 
![image](https://user-images.githubusercontent.com/1933165/70448559-70eaab00-1a98-11ea-8f43-db14847bc9fa.png)

**Comment by shlomiassaf** [comment]
`pbl-ngrid-row-visually-hidden` implies in name that it's visually hidden but not actually hidden so this is why `collapsed` is used.

I see that it there's an issue in FF, I really don't understand why... strange.

I can also see that changing to "hidden" does the job, i'll do some more tests and change to this behaviour by setting the style explicitly on the DOM element, i'll leave the class as is for back compatibility and because that's what it is supposed to do.
